Models/UserModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Ease.Extract.Web.Classes;

namespace Ease.Extract.Web.Models
{
    public class UserModel
    {
        [Required]
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

Controllers/EaseExtractDataController.cs
using Ease.Data;
using Ease.Data.Sql;
using Ease.Model.Extract;
using Ease.Util;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.HtmlControls;

namespace Ease.Extract.Web.Controllers
{
    public class EaseExtractDataController : Controller
    {


        internal EaseDataAccess DataAccess = new EaseDataAccess(new SqlDataAccessCommon(), new SqlDataAccessAudit(), new SqlDataAccessAccount(), new SqlDataAccessLaborStandards(), new SqlDataAccessExtract());
        public FileContentResult GetMetricsData()
        {
            string visibleColumnNames = "ID, OrganizationID, SiteID, OrgName, SiteName, DateFrom, DateTo, PctAuditsCompleted, NumActiveUsers, PctMitigationsClosed, EnvironmentID";
            string language = "EN-US";

            //sort by ID in the sitesintrial table

            IEnumerable<UsageData> ExtractedData = DataAccess.Extract.DataFromEaseExtract();
            CSVReponseHelper csvResponseHelper = new CSVReponseHelper(DataAccess.Common);
            byte[] dataToExport = csvResponseHelper.WriteCsvToMemory<UsageData>(ExtractedData, language, visibleColumnNames);
            return File(dataToExport, "text/csv", "SalesMetrics.csv" + " " + DateTime.Today);
        }

        [Route("Dashboard"), HttpGet]
        public ActionResult Dashboard()
        {
            IEnumerable<UsageData> model = DataAccess.Extract.ExtractFromSitesInTrial();
            if (model != null)
            {
                return View("Dashboard", model);
            }
            else
            {
                return Redirect("User/Index");
            }
        }
    }

}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Ease.Extract.Web.Models;
using Ease.Data;
using Ease.Model.Extract;
using Ease.Data.Sql;
using System.IO;
using Owin;
using Ease.Util;
using System.Web.Configuration;
using System.Configuration;
using System.Text;
using Ease.Extract.Web.Classes;


namespace Ease.Extract.Web.Controllers
{
    [RoutePrefix("User")]
    public class UserController : Controller
    {
        
        [Route("Index"), HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }



        [Route("Login"), HttpPost]
        public ActionResult Login(UserModel user)
        {
            if (ModelState.IsValid)
            {
                if (IsValid(user.UserName, user.Password))
                {
                    return RedirectToAction("Index", "user");
                }
                else
                {
                    ModelState.AddModelError("", "Login data is incorrect!");
                }
            }
            return View(user);
        }
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "user");
        }
        private bool IsValid(string username, string password)
        {
            string hashedPassword = HashUtilWrapper.Hash(password);
            string systemUsername = ConfigurationManager.AppSettings["PFUserName"];
            string systemPassword = ConfigurationManager.AppSettings["PFPassword"];
#if DEBUG
            Console.WriteLine(systemPassword);
            Console.WriteLine(systemUsername);
#endif

            if (string.Equals(hashedPassword, systemPassword, StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
            else
            {
                return false;
            }

        }
    }
}

Views/EaseExtractData/Dashboard.cshtml
@model IEnumerable<Ease.Model.Extract.UsageData>

@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dashboard</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrganizationID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SiteID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrgName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SiteName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateFrom)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.DateTo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PctAuditsCompleted)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumActiveUsers)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PctMitigationsClosed)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EnvironmentID)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.ID)
            </td>
            <td>
                @Html.DisplayFor(model => item.OrganizationID)
            </td>
            <td>
                @Html.DisplayFor(model => item.SiteID)
            </td>
            <td>
                @Html.DisplayFor(model => item.OrgName)
            </td>
            <td>
                @Html.DisplayFor(model => item.SiteName)
            </td>
            <td>
                @Html.DisplayFor(model => item.DateFrom)
            </td>
            <td>
                @Html.DisplayFor(model => item.DateTo)
            </td>
            <td>
                @Html.DisplayFor(model => item.PctAuditsCompleted)
            </td>
            <td>
                @Html.DisplayFor(model => item.NumActiveUsers)
            </td>
            <td>
                @Html.DisplayFor(model => item.PctMitigationsClosed)
            </td>
            <td>
                @Html.DisplayFor(model => item.EnvironmentID)
            </td>

        </tr>
    }

</table>


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/scripts/dashboard.css")" rel="stylesheet" type="text/css" />
    @RenderSection("scripts", false)
</head>
<body>
    <div style="width: auto; background-color: #728ea7;">
        @if (Request.IsAuthenticated)
        {
            <strong>@Html.Encode(User.Identity.Name)</strong>
            @Html.ActionLink("Sign Out", "Logout", "User")
        }
        else
        {
            <span> | </span>
            @Html.ActionLink("Sign In", "Login", "User")
        }
    </div>

    @RenderBody()


    @RenderSection("scripts", required: false)
</body>
</html>

Views/User/Index.cshtml
@using Ease.Extract.Web.Controllers
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "Home";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Home </title>
</head>
<body>
    <div>
        @Html.ActionLink("Get Metrics", "GetMetricsData", "EaseExtractData");
    </div>
    <div>
        @Html.ActionLink("See Dashboard", "Dashboard", "EaseExtractData")
    </div>
</body>
</html>

Views/User/Login.cshtml
@model Ease.Extract.Web.Models.UserModel
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true, "Login failed. Check your login details.");
    <div>
        <fieldset>
            <legend>Login</legend>
            <div class="editor-label">
                @Html.LabelFor(u => u.UserName)
            </div>
            <div class="editor-field">
                @Html.TextBoxFor(u => u.UserName)
                @Html.ValidationMessageFor(u => u.UserName)
            </div>
            <div class="editor-label">
                @Html.LabelFor(u => u.Password)
            </div>
            <div class="editor-field">
                @Html.PasswordFor(u => u.Password)
                @Html.ValidationMessageFor(u => u.Password)
            </div>
            <input type="submit" value="Log In" />
        </fieldset>
    </div>
}